"use client";
import {useEffect,useRef,useState} from "react";
import {createClient,type User} from "@supabase/supabase-js";
import {Zap,Plus,Smartphone,Search,Banknote,ArrowUpRight,BatteryCharging,Check,RefreshCw,Lock,LogOut} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";

type Device={id:number;customer:string;contact:string;device:string;notes:string;amount:number;payment:string;status:string;created_at:string;paid_at:string|null;collected_at:string|null;pending?:boolean;sync_error?:string};
type QueueOp={opId:string;kind:"create";localId:number;payload:{customer:string;contact:string;device:string;notes:string;amount:number;payment:string}}|{opId:string;kind:"update";id:number;action:string};
const supabase=createClient("https://rtouphsrjhwgadqeqzfw.supabase.co","sb_publishable_FuXdVibS9tiawemhwZMtUQ_dCqQALQn");
const CACHE_KEY="pa-gerrys-register-cache",QUEUE_KEY="pa-gerrys-sync-queue";
const money=(n:number)=>new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(n/100);
const ticket=(n:number)=>n<0?`LOCAL-${String(Math.abs(n)).slice(-4)}`:`PG-${String(n).padStart(4,"0")}`;
const readJson=<T,>(key:string,fallback:T):T=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch{return fallback;}};
const writeJson=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
const queueOps=()=>readJson<QueueOp[]>(QUEUE_KEY,[]);
const setQueue=(ops:QueueOp[])=>writeJson(QUEUE_KEY,ops);
const cacheRows=(rows:Device[])=>writeJson(CACHE_KEY,rows);

export default function Home(){
 const [user,setUser]=useState<User|null>(null),[authLoading,setAuthLoading]=useState(true),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(""),[login,setLogin]=useState({email:"",password:""});
 const [rows,setRows]=useState<Device[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[syncing,setSyncing]=useState(false),[online,setOnline]=useState(true),[pendingCount,setPendingCount]=useState(0),[error,setError]=useState(""),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("active");
 const [form,setForm]=useState({customer:"",contact:"",device:"",notes:"",amount:"",payment:"unpaid"});
 const syncingRef=useRef(false);

 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive)setUser(data.session?.user??null);}).catch(()=>setAuthError("Could not check login. Please refresh.")).finally(()=>{if(alive)setAuthLoading(false);});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);setAuthLoading(false);});return()=>{alive=false;subscription.unsubscribe();};},[]);
 useEffect(()=>{setOnline(navigator.onLine);setPendingCount(queueOps().length);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});const on=()=>setOnline(true);const off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off);};},[]);
 useEffect(()=>{if(user){const cached=readJson<Device[]>(CACHE_KEY,[]);if(cached.length)setRows(cached);refresh();}else{setRows([]);setLoading(false);}},[user]);
 useEffect(()=>{if(user&&online)syncPending();},[user,online]);

 async function signIn(e:React.FormEvent){e.preventDefault();setAuthBusy(true);setAuthError("");try{const {error}=await supabase.auth.signInWithPassword({email:login.email.trim(),password:login.password});if(error)throw error;setLogin({email:"",password:""});}catch(e){setAuthError(e instanceof Error?e.message:"Could not sign in. Check the staff email and password.");}finally{setAuthBusy(false);}}
 async function signOut(){setAuthBusy(true);setMessage("");setError("");await supabase.auth.signOut();setAuthBusy(false);}
 async function authHeaders(){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw Error("Please sign in again.");return {"Content-Type":"application/json",Authorization:`Bearer ${token}`};}
 function remember(next:Device[]|((rows:Device[])=>Device[])){setRows(current=>{const value=typeof next==="function"?(next as (rows:Device[])=>Device[])(current):next;cacheRows(value);return value;});}
 function enqueue(op:QueueOp){const next=[...queueOps(),op];setQueue(next);setPendingCount(next.length);}
 function localUpdate(row:Device,action:string):Device{const now=new Date().toISOString();if(action==="cash"||action==="transfer")return {...row,payment:action,paid_at:row.paid_at||now,pending:true};if(action==="ready")return {...row,status:"ready",pending:true};return {...row,status:"collected",collected_at:row.collected_at||now,pending:true};}
 function createLocal(payload:QueueOp&{kind:"create"}){const now=new Date().toISOString();const local:Device={id:payload.localId,customer:payload.payload.customer,contact:payload.payload.contact,device:payload.payload.device,notes:payload.payload.notes,amount:payload.payload.amount,payment:payload.payload.payment,status:"charging",created_at:now,paid_at:payload.payload.payment==="unpaid"?null:now,collected_at:null,pending:true};remember(x=>[local,...x]);enqueue(payload);setMessage(`${ticket(local.id)} saved offline. It will sync when internet returns.`);}
 async function refresh(){setLoading(true);try{if(!navigator.onLine)throw Error("Offline. Showing saved register on this device.");await syncPending();const r=await fetch("/api/devices",{headers:await authHeaders()});const d=await r.json();if(!r.ok)throw Error(d.error);const pending=readJson<Device[]>(CACHE_KEY,[]).filter(v=>v.pending);const merged=[...pending,...d.devices];remember(merged);setError("");}catch(e){const cached=readJson<Device[]>(CACHE_KEY,[]);if(cached.length){remember(cached);setError(e instanceof Error?e.message:"Offline. Showing saved register on this device.");}else setError(e instanceof Error?e.message:"Could not load records. Please retry.");}finally{setLoading(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!user)return;setBusy(true);setError("");setMessage("");const payload={customer:form.customer.trim(),contact:form.contact.trim(),device:form.device.trim(),notes:form.notes.trim(),amount:Math.round(Number(form.amount)*100),payment:form.payment};try{if(!navigator.onLine)throw Error("offline");const r=await fetch("/api/devices",{method:"POST",headers:await authHeaders(),body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);remember(x=>[d.device,...x]);setMessage(`${ticket(d.device.id)} saved. Write this ticket number on the device tag.`);}catch(e){createLocal({opId:crypto.randomUUID(),kind:"create",localId:-Date.now(),payload});}finally{setForm({customer:"",contact:"",device:"",notes:"",amount:"",payment:"unpaid"});setBusy(false);}}
 async function update(id:number,action:string){if(!user)return;setBusy(true);setError("");try{if(!navigator.onLine||id<0)throw Error("offline");const r=await fetch("/api/devices",{method:"PATCH",headers:await authHeaders(),body:JSON.stringify({id,action})});const d=await r.json();if(!r.ok)throw Error(d.error);remember(x=>x.map(v=>v.id===id?d.device:v));setMessage(`${ticket(id)} updated.`);}catch(e){remember(x=>x.map(v=>v.id===id?localUpdate(v,action):v));enqueue({opId:crypto.randomUUID(),kind:"update",id,action});setMessage(`${ticket(id)} updated offline. It will sync when internet returns.`);}finally{setBusy(false);}}
 async function syncPending(){if(syncingRef.current||!user||!navigator.onLine)return;const ops=queueOps();if(!ops.length){setPendingCount(0);return;}syncingRef.current=true;setSyncing(true);let remaining:QueueOp[]=[];const idMap=new Map<number,number>();try{const headers=await authHeaders();for(const op of ops){try{if(op.kind==="create"){const r=await fetch("/api/devices",{method:"POST",headers,body:JSON.stringify(op.payload)});const d=await r.json();if(!r.ok)throw Error(d.error);idMap.set(op.localId,d.device.id);remember(x=>x.map(v=>v.id===op.localId?d.device:v));}else{const id=op.id<0?idMap.get(op.id):op.id;if(!id)throw Error("Waiting for offline check-in to sync.");const r=await fetch("/api/devices",{method:"PATCH",headers,body:JSON.stringify({id,action:op.action})});const d=await r.json();if(!r.ok)throw Error(d.error);remember(x=>x.map(v=>v.id===op.id||v.id===id?d.device:v));}}catch{remaining.push(op);}}setQueue(remaining);setPendingCount(remaining.length);if(ops.length&&!remaining.length)setMessage("Offline changes synced.");}finally{syncingRef.current=false;setSyncing(false);}}

 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool||!user)return;const ac=new AbortController();Promise.resolve(ctx.registerTool({name:"search_charging_register",description:"Search saved tickets and show matching records in the register.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof (input as any).query!=="string")throw Error("query must be text");const q=(input as any).query;setQuery(q);setFilter("all");return {devices:rows.filter(r=>[r.customer,r.device,r.contact,ticket(r.id)].join(" ").toLowerCase().includes(q.toLowerCase()))};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[rows,user]);

 if(authLoading)return <div className="auth-shell"><div className="auth-card"><span className="auth-mark"><Zap size={28} fill="currentColor"/></span><h1>PA GERRYS</h1><p>Checking staff login...</p></div></div>;
 if(!user)return <div className="auth-shell"><section className="auth-card"><span className="auth-mark"><Lock size={28}/></span><p className="eyebrow">PA GERRYS CHARGING DESK</p><h1>Staff login</h1><p className="subtle">Sign in with the staff account from Supabase.</p>{authError&&<div role="alert" className="alert error">{authError}</div>}<form onSubmit={signIn} className="auth-form"><label>Email<Input required type="email" autoComplete="email" placeholder="staff@email.com" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Password<Input required type="password" autoComplete="current-password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><Button type="submit" className="submit" disabled={authBusy}>{authBusy?"Signing in...":"Sign in"}</Button></form><small>Staff users must exist in your Supabase project.</small></section></div>;

 const today=new Date().toLocaleDateString(),paidToday=rows.filter(r=>r.paid_at&&new Date(r.paid_at).toLocaleDateString()===today);
 const cash=paidToday.filter(r=>r.payment==="cash").reduce((s,r)=>s+r.amount,0),transfer=paidToday.filter(r=>r.payment==="transfer").reduce((s,r)=>s+r.amount,0),active=rows.filter(r=>r.status!=="collected"),unpaid=rows.filter(r=>r.payment==="unpaid");
 const visible=rows.filter(r=>(filter==="all"||filter==="active"&&r.status!=="collected"||filter==="unpaid"&&r.payment==="unpaid"||filter===r.status)&&[r.customer,r.device,r.contact,ticket(r.id)].join(" ").toLowerCase().includes(query.toLowerCase()));

 return <div className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Zap size={24} fill="currentColor"/></span><span>PA GERRYS<small>CHARGING DESK</small></span></a><div className="staff-area"><div className="date"><span>STAFF LOGIN</span><strong>{user.email}</strong></div><Button variant="outline" onClick={signOut} disabled={authBusy}><LogOut size={16}/> Sign out</Button></div></header><main>
 <div className="heading"><div><p className="eyebrow">EVERY DEVICE. EVERY PAYMENT.</p><h1>Your charging desk</h1><p className="subtle">Check devices in. Keep payments in order.</p></div><span className={`desk-label ${online?"online":"offline"}`}><BatteryCharging size={19}/>{online?syncing?"Syncing changes":"Online":`Offline${pendingCount?` - ${pendingCount} waiting`:''}`}</span></div>
 <section className="stats" aria-label="Shop summary"><article className="stat dark"><span>Devices at the shop <BatteryCharging size={20}/></span><strong>{loading?"-":active.length}</strong><small>{active.filter(r=>r.status==="ready").length} ready for collection</small></article><article className="stat"><span>Cash received today <Banknote size={20}/></span><strong>{loading?"-":money(cash)}</strong><small>Recorded cash payments</small></article><article className="stat"><span>Transfers today <ArrowUpRight size={20}/></span><strong>{loading?"-":money(transfer)}</strong><small>Confirmed transfers only</small></article><article className="stat"><span>Unpaid balance <span className="amber-mark"/></span><strong>{loading?"-":money(unpaid.reduce((s,r)=>s+r.amount,0))}</strong><small>{unpaid.length} unpaid devices</small></article></section>
 {!online&&<div role="status" className="alert offline-note">Offline mode is on. New work is saved on this device and will sync when internet returns.</div>}{online&&pendingCount>0&&<div role="status" className="alert offline-note">{pendingCount} offline change{pendingCount===1?"":"s"} waiting to sync.</div>}{error&&<div role="alert" className="alert error">{error}<Button variant="outline" onClick={refresh}>Retry loading</Button></div>}{message&&<div role="status" className="alert success"><Check size={18}/>{message}</div>}
 <div className="workspace"><section className="checkin panel"><div className="panel-title"><span className="mini-icon"><Plus size={20}/></span><div><h2>New check-in</h2><p>One ticket for each device.</p></div></div><form onSubmit={save}><label>Customer name<Input required maxLength={100} placeholder="e.g. Alex Johnson" value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label>Phone number <small>optional</small><Input type="tel" maxLength={40} placeholder="Contact number" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><label>Device / model<Input required maxLength={160} placeholder="e.g. Samsung A15, black" value={form.device} onChange={e=>setForm({...form,device:e.target.value})}/></label><label>Charging fee<Input required type="number" min="0" max="10000000" step="0.01" placeholder="0.00" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><fieldset><legend>Payment</legend><div className="payment-options">{["unpaid","cash","transfer"].map(p=><label key={p} className={form.payment===p?"chosen":""}><input type="radio" name="payment" value={p} checked={form.payment===p} onChange={()=>setForm({...form,payment:p})}/>{p==="unpaid"?"Unpaid":p==="cash"?"Cash":"Transfer"}</label>)}</div><p className="field-hint">Select transfer only after confirming receipt.</p></fieldset><label>Device notes <small>optional</small><Input maxLength={500} placeholder="Case colour, cable, existing damage..." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><Button type="submit" className="submit" disabled={busy||loading}><Plus size={18}/>{busy?"Saving...":"Check in device"}</Button></form><div className="ticket-note"><span>01</span><p>Tag the device with its ticket number before putting it on charge.</p></div></section>
 <section className="register panel"><div className="register-heading"><div><h2>Device register <span className="count">{rows.length}</span></h2><p>From drop-off to collection.</p></div><Button aria-label="Refresh register" variant="ghost" onClick={refresh} disabled={loading||busy}><RefreshCw size={18}/></Button></div><div className="register-controls"><div className="search"><Search size={18}/><Input aria-label="Search device register" placeholder="Search name, device or ticket..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter devices" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">At the shop</option><option value="ready">Ready to collect</option><option value="unpaid">Unpaid</option><option value="collected">Collected</option><option value="all">All records</option></select></div>
 <div className="records">{loading?<div className="empty"><RefreshCw size={30}/><h3>Loading your register...</h3></div>:visible.length===0?<div className="empty"><span className="empty-icon"><Smartphone size={35}/><Zap size={20}/></span><h3>{rows.length?"No matching devices":"Your first device starts here"}</h3><p>{rows.length?"Try another search or filter.":"Add a device using the check-in form. Its ticket and payment details will appear here."}</p>{!rows.length&&<span className="empty-tag">CHECK IN - CHARGE - COLLECT</span>}</div>:visible.map(r=><article className={`device-row ${r.pending?"pending-row":""}`} key={r.id}><div className="device-main"><span className="device-icon"><Smartphone size={22}/></span><div><div className="device-top"><strong>{r.device}</strong><span className={`badge ${r.status}`}>{r.status==="ready"?"Ready":r.status==="collected"?"Collected":"Charging"}</span>{r.pending&&<span className="badge pending">Waiting to sync</span>}</div><p>{r.customer}{r.contact&&` - ${r.contact}`}</p><small>{ticket(r.id)} - In {new Date(r.created_at).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small>{r.notes&&<p className="notes">{r.notes}</p>}</div><div className="price"><strong>{money(r.amount)}</strong><span className={`pay ${r.payment}`}>{r.payment==="unpaid"?"Unpaid":r.payment==="cash"?"Paid - Cash":"Paid - Transfer"}</span></div></div><div className="row-actions">{r.payment==="unpaid"&&<><Button variant="outline" disabled={busy} onClick={()=>update(r.id,"cash")}>Paid cash</Button><Button variant="outline" disabled={busy} onClick={()=>update(r.id,"transfer")}>Transfer received</Button></>}{r.status==="charging"&&<Button variant="outline" disabled={busy} onClick={()=>update(r.id,"ready")}>Mark ready</Button>}{r.status!=="collected"&&<Button disabled={busy||r.payment==="unpaid"} title={r.payment==="unpaid"?"Record payment before collection":"Mark device collected"} onClick={()=>update(r.id,"collected")}>Collect device <Check size={15}/></Button>}{r.collected_at&&<small>Collected {new Date(r.collected_at).toLocaleString()}</small>}</div></article>)}</div><footer className="register-footer"><span>{visible.length} devices shown</span><span>{pendingCount?`${pendingCount} waiting to sync`:"Keep the ticket until collection"}</span></footer></section></div><footer className="page-footer"><strong>PA GERRYS</strong><span>Charging made orderly.</span></footer></main></div>;
}
