"use client";
import {useEffect,useState} from "react";
import {Zap,Plus,Smartphone,Search,Banknote,ArrowUpRight,BatteryCharging,Check,RefreshCw} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
type Device={id:number;customer:string;contact:string;device:string;notes:string;amount:number;payment:string;status:string;created_at:string;paid_at:string|null;collected_at:string|null};
const money=(n:number)=>new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(n/100);
const ticket=(n:number)=>`PG-${String(n).padStart(4,"0")}`;
export default function Home(){
 const [rows,setRows]=useState<Device[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("active");
 const [form,setForm]=useState({customer:"",contact:"",device:"",notes:"",amount:"",payment:"unpaid"});
 async function refresh(){setLoading(true);try{const r=await fetch("/api/devices");const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.devices);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load records. Please retry.");}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/devices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,amount:Math.round(Number(form.amount)*100)})});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(x=>[d.device,...x]);setMessage(`${ticket(d.device.id)} saved. Write this ticket number on the device tag.`);setForm({customer:"",contact:"",device:"",notes:"",amount:"",payment:"unpaid"});}catch(e){setError(e instanceof Error?e.message:"Could not save. Your details are still here.");}finally{setBusy(false);}}
 async function update(id:number,action:string){setBusy(true);setError("");try{const r=await fetch("/api/devices",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(x=>x.map(v=>v.id===id?d.device:v));setMessage(`${ticket(id)} updated.`);}catch(e){setError(e instanceof Error?e.message:"Could not update. Please retry.");}finally{setBusy(false);}}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();Promise.resolve(ctx.registerTool({name:"search_charging_register",description:"Search saved tickets and show matching records in the register.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof (input as any).query!=="string")throw Error("query must be text");const q=(input as any).query;setQuery(q);setFilter("all");return {devices:rows.filter(r=>[r.customer,r.device,r.contact,ticket(r.id)].join(" ").toLowerCase().includes(q.toLowerCase()))};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[rows]);
 const today=new Date().toLocaleDateString(),paidToday=rows.filter(r=>r.paid_at&&new Date(r.paid_at).toLocaleDateString()===today);
 const cash=paidToday.filter(r=>r.payment==="cash").reduce((s,r)=>s+r.amount,0),transfer=paidToday.filter(r=>r.payment==="transfer").reduce((s,r)=>s+r.amount,0),active=rows.filter(r=>r.status!=="collected"),unpaid=rows.filter(r=>r.payment==="unpaid");
 const visible=rows.filter(r=>(filter==="all"||filter==="active"&&r.status!=="collected"||filter==="unpaid"&&r.payment==="unpaid"||filter===r.status)&&[r.customer,r.device,r.contact,ticket(r.id)].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <div className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Zap size={24} fill="currentColor"/></span><span>PA GERRYS<small>CHARGING DESK</small></span></a><div className="date"><span>SHOP REGISTER</span><strong>{new Date().toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"long",year:"numeric"})}</strong></div></header><main>
 <div className="heading"><div><p className="eyebrow">EVERY DEVICE. EVERY PAYMENT.</p><h1>Your charging desk</h1><p className="subtle">Check devices in. Keep payments in order.</p></div><span className="desk-label"><BatteryCharging size={19}/> Ready for the day</span></div>
 <section className="stats" aria-label="Shop summary"><article className="stat dark"><span>Devices at the shop <BatteryCharging size={20}/></span><strong>{loading?"—":active.length}</strong><small>{active.filter(r=>r.status==="ready").length} ready for collection</small></article><article className="stat"><span>Cash received today <Banknote size={20}/></span><strong>{loading?"—":money(cash)}</strong><small>Recorded cash payments</small></article><article className="stat"><span>Transfers today <ArrowUpRight size={20}/></span><strong>{loading?"—":money(transfer)}</strong><small>Confirmed transfers only</small></article><article className="stat"><span>Unpaid balance <span className="amber-mark"/></span><strong>{loading?"—":money(unpaid.reduce((s,r)=>s+r.amount,0))}</strong><small>{unpaid.length} unpaid devices</small></article></section>
 {error&&<div role="alert" className="alert error">{error}<Button variant="outline" onClick={refresh}>Retry loading</Button></div>}{message&&<div role="status" className="alert success"><Check size={18}/>{message}</div>}
 <div className="workspace"><section className="checkin panel"><div className="panel-title"><span className="mini-icon"><Plus size={20}/></span><div><h2>New check-in</h2><p>One ticket for each device.</p></div></div><form onSubmit={save}><label>Customer name<Input required maxLength={100} placeholder="e.g. Alex Johnson" value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label>Phone number <small>optional</small><Input type="tel" maxLength={40} placeholder="Contact number" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><label>Device / model<Input required maxLength={160} placeholder="e.g. Samsung A15, black" value={form.device} onChange={e=>setForm({...form,device:e.target.value})}/></label><label>Charging fee<Input required type="number" min="0" max="10000000" step="0.01" placeholder="0.00" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><fieldset><legend>Payment</legend><div className="payment-options">{["unpaid","cash","transfer"].map(p=><label key={p} className={form.payment===p?"chosen":""}><input type="radio" name="payment" value={p} checked={form.payment===p} onChange={()=>setForm({...form,payment:p})}/>{p==="unpaid"?"Unpaid":p==="cash"?"Cash":"Transfer"}</label>)}</div><p className="field-hint">Select transfer only after confirming receipt.</p></fieldset><label>Device notes <small>optional</small><Input maxLength={500} placeholder="Case colour, cable, existing damage…" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><Button type="submit" className="submit" disabled={busy||loading}><Plus size={18}/>{busy?"Saving…":"Check in device"}</Button></form><div className="ticket-note"><span>01</span><p>Tag the device with its ticket number before putting it on charge.</p></div></section>
 <section className="register panel"><div className="register-heading"><div><h2>Device register <span className="count">{rows.length}</span></h2><p>From drop-off to collection.</p></div><Button aria-label="Refresh register" variant="ghost" onClick={refresh} disabled={loading||busy}><RefreshCw size={18}/></Button></div><div className="register-controls"><div className="search"><Search size={18}/><Input aria-label="Search device register" placeholder="Search name, device or ticket…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter devices" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">At the shop</option><option value="ready">Ready to collect</option><option value="unpaid">Unpaid</option><option value="collected">Collected</option><option value="all">All records</option></select></div>
 <div className="records">{loading?<div className="empty"><RefreshCw size={30}/><h3>Loading your register…</h3></div>:visible.length===0?<div className="empty"><span className="empty-icon"><Smartphone size={35}/><Zap size={20}/></span><h3>{rows.length?"No matching devices":"Your first device starts here"}</h3><p>{rows.length?"Try another search or filter.":"Add a device using the check-in form. Its ticket and payment details will appear here."}</p>{!rows.length&&<span className="empty-tag">CHECK IN → CHARGE → COLLECT</span>}</div>:visible.map(r=><article className="device-row" key={r.id}><div className="device-main"><span className="device-icon"><Smartphone size={22}/></span><div><div className="device-top"><strong>{r.device}</strong><span className={`badge ${r.status}`}>{r.status==="ready"?"Ready":r.status==="collected"?"Collected":"Charging"}</span></div><p>{r.customer}{r.contact&&` · ${r.contact}`}</p><small>{ticket(r.id)} · In {new Date(r.created_at).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small>{r.notes&&<p className="notes">{r.notes}</p>}</div><div className="price"><strong>{money(r.amount)}</strong><span className={`pay ${r.payment}`}>{r.payment==="unpaid"?"Unpaid":r.payment==="cash"?"Paid · Cash":"Paid · Transfer"}</span></div></div><div className="row-actions">{r.payment==="unpaid"&&<><Button variant="outline" disabled={busy} onClick={()=>update(r.id,"cash")}>Paid cash</Button><Button variant="outline" disabled={busy} onClick={()=>update(r.id,"transfer")}>Transfer received</Button></>}{r.status==="charging"&&<Button variant="outline" disabled={busy} onClick={()=>update(r.id,"ready")}>Mark ready</Button>}{r.status!=="collected"&&<Button disabled={busy||r.payment==="unpaid"} title={r.payment==="unpaid"?"Record payment before collection":"Mark device collected"} onClick={()=>update(r.id,"collected")}>Collect device <Check size={15}/></Button>}{r.collected_at&&<small>Collected {new Date(r.collected_at).toLocaleString()}</small>}</div></article>)}</div><footer className="register-footer"><span>{visible.length} devices shown</span><span>Keep the ticket until collection</span></footer></section></div><footer className="page-footer"><strong>PA GERRYS</strong><span>Charging made orderly.</span></footer></main></div>;
}
